---
- name: Setup and run Minecraft server on EC2 instance
  hosts: minecraft
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest

    - name: Install Docker package
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is running and enabled on startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Launch Minecraft server using Docker
      community.docker.docker_container:
        name: minecraft-server
        image: itzg/minecraft-server
        state: started
        ports:
          - "25565:25565"
        restart_policy: always
        env:
          EULA: "TRUE"
